# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twittar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-creation_date']},
        ),
    ]
