# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twittar_app', '0002_auto_20180314_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(help_text='Max number of characters: 140', max_length=140, verbose_name='Your message'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(help_text='Max number of characters: 140', max_length=140, verbose_name='Your message'),
        ),
    ]
