# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twittar_app', '0003_auto_20180314_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
    ]
